### ISSUE TITLE
Missing mix-manifest.json warning

### ISSUE THREAD

**Issue by raulsperoni** [jeffreyvr/tailpress#11]
Hi, this boilerplate is great thank you!

I'm getting this warning:

Warning: file_get_contents(/var/www/html/wp-content/themes/tailpress/mix-manifest.json): failed to open stream: No such file or directory in /var/www/html/wp-content/themes/tailpress/functions.php on line 26

mix-manifest.json exists in the theme folder but it doesn't get copied. I'm running this with docker. 

Thanks!

**Comment by raulsperoni** [comment]
It was ignored in .gitignore

**Comment by jeffreyvr** [comment]
Thanks for reporting back @raulsperoni! I wasn't able to test it with Docker yet. Glad it is resolved!
