### ISSUE TITLE
Block editor (Gutenberg) freezes when trying to add the custom HTML-block. 

### ISSUE THREAD

**Issue by joelgrodriguez** [jeffreyvr/tailpress#12]
Problem:
Whenever I try to add an HTML embed or images to the guttenberg editor it freezes and it does work. 

I uninstalled my theme and installed a fresh copy and still have the same issue. 

I then uninstalled and installed a basic copy of _underscores and then I was able to embed.

Here is a video recreating the problem:
[Video Link](https://share.vidyard.com/watch/UqVCP2tr2rfg4MKMoErxBr?)

If I remove all the styles from editor-style.css the issue is resolved and I am able to embed the styles. Also, the editor page opens quicker. I will see if I can track down what is causing it but I am not experienced enough. 

Thanks

**Comment by jeffreyvr** [comment]
Thanks for the video @joelgrodriguez.

I am aware of editor-styles.css slowing down the editor, but didn't know it also freezes the custom html-block. 

I mostly do a production build of the CSS and then comment out this line so that editor-styles.css does not recompile:
https://github.com/jeffreyvr/tailpress/blob/master/webpack.mix.js#L9

This will speed also up your compiling a lot (when using `npm run watch`).

I will then uncomment it when I do a new production build or when I really need to see some changes within the editor.

In this video I quickly mentioned it:
https://youtu.be/g9q2d5jRXMY?t=267

I'm wondering if there is a way that this could be optimised out of the box.

**Comment by joelgrodriguez** [comment]
So I found a solution. I think. 

on functions.php line 96. Add 'editor-styles' as a parameter and it works!
I have no idea why though. 

`add_editor_style('editor-styles');`

I tested this on my theme and on a fresh install. Solves the issue for me and works as expected.

**Comment by jeffreyvr** [comment]
@joelgrodriguez Thanks for sharing. I think that your change results in the theme CSS not being loaded in the block editor. This will speed up the editor and it will also solve the freeze issue. But you would end up with the default styling of the block editor. See the below comparison. Or am I missing something here?

With your change applied:
<img width="717" alt="Screenshot 2021-03-10 at 11 37 45" src="https://user-images.githubusercontent.com/9550079/110616720-2a04cd00-8195-11eb-896a-6922835cc5c2.png">

With the current code:
<img width="731" alt="Screenshot 2021-03-10 at 11 38 11" src="https://user-images.githubusercontent.com/9550079/110616750-338e3500-8195-11eb-8e94-0e72d445b526.png">

**Comment by jeffreyvr** [comment]
We could by default only compile editor-styles.css when a production build is being done.

```js
if ( mix.inProduction() ) {
    mix.postCss("resources/css/editor-style.css", "./");
}
```

That way, out of the box, this issue will not occur. The only downside is that for changes to your CSS to also be available in the block editor, you would have to run `npm run production`.

**Comment by jeffreyvr** [comment]
Another note, Adam Wathan just announced the [Tailwind CSS JIT compiler](https://github.com/tailwindlabs/tailwindcss-jit) which makes compiling a lot faster for development builds as well. This makes compiling editor-style.css on dev builds faster as well.

I tried it out on the jit branche (https://github.com/jeffreyvr/tailpress/tree/jit) and with some minor tweaks got it working. Check out the results:

Before
<img width="682" alt="Screenshot 2021-03-16 at 00 00 24" src="https://user-images.githubusercontent.com/9550079/111232070-a1e65380-85ea-11eb-83fd-4b2a305099a5.png">

After
<img width="682" alt="Screenshot 2021-03-15 at 23 59 41" src="https://user-images.githubusercontent.com/9550079/111232072-a3178080-85ea-11eb-9efb-2e5a07c4ad52.png">

**Comment by JonasBrandit** [comment]
@jeffreyvr 
I have also followed Adam's work with JIT via twitter and it looks awesome. Must really try it and together with your awesome boilerplate this fits well with my upcoming project with Woo
