### ISSUE TITLE
Why is lodash required?

### ISSUE THREAD

**Issue by justingolden21** [jeffreyvr/tailpress#130]
`tailwind.config.js` has:

`const _ = require("lodash");`

But this is unused anywhere in the project.

(I also found some unnecessary code in the form of HTML element IDs)

Thank you.

**Comment by jeffreyvr** [comment]
Appears to be a leftover from when it was needed in an earlier version. Has been [removed](https://github.com/jeffreyvr/tailpress/commit/f338dadf71f52574ed2ea1f85b400adee6c6decb) now.
