### ISSUE TITLE
Aria support for tailpress

### ISSUE THREAD

**Issue by seblanc** [jeffreyvr/tailpress#14]
I installed and started to use your Tailpress theme and it is awesome (thanks).
I built a primary menu which shoes correctly on the website, but I don't know how to handle the "aria" tags and css styles when the menu item is selected/hovered or is a sub-item (and should be hidden).

Thank you in advance for your help!

**Comment by JonasBrandit** [comment]
Is this something like this you are talking about?
https://github.com/jeffreyvr/tailpress/issues/10#issuecomment-779216448

**Comment by seblanc** [comment]
This helped hidding the subitem and not displaying it all the time, but what I'm missing is the js code that shows display the subitem, but more importantly, what I miss is the change of class to which item (page) in the selected.

Any idea?

**Comment by jeffreyvr** [comment]
The example that @JonasBrandit shared provides a submenu solution without JS needed.

I'm not really an expert when it comes to aria-labelling. You can add ab aria-label for the navigation container (see snippet) below. Menu items are provided with aria-labels automatically (by WordPress).

If you would like to add a aria-label to the navigation container, you could do this:

```php
wp_nav_menu(
	array(
		'container'            => 'nav', // Make sure to wrap it with a nav element.
		'container_id'         => 'primary-menu',
		'container_aria_label' => 'Your Aria Label Here', // <---
		'container_class'      => 'hidden bg-gray-100 mt-4 p-4 lg:mt-0 lg:p-0 lg:bg-transparent lg:block',
		'menu_class'           => 'lg:flex lg:-mx-4',
		'theme_location'       => 'primary',
		'li_class'             => 'lg:mx-4',
		'fallback_cb'          => false,
	)
);
```

When it comes to the visibility state and aria-labels (For example: `aria-expanded="true"`), you would probably need to use JS (example below, but this is probably not a great way to go about it). If you figure something out to better support this, feel free to share it here.

```js
jQuery('.menu-item-has-children').hover(function(){
      jQuery(this).find('.sub-menu').attr('aria-expanded', 'true');
}, function() {
      jQuery(this).find('.sub-menu').attr('aria-expanded, 'false');
});
```

**Comment by seblanc** [comment]
Thank for the return. My issue was to get the menu item change style upon the selected page. After watching your [video](https://www.youtube.com/watch?v=g9q2d5jRXMY), I realized I have to put my code in the ./resources/css/custom.css:

``` css
.current_page_item, .current-menu-parent {
    font-weight: bold;
    @apply text-primary;
}
```
