### ISSUE TITLE
Is Tailwind JIT working correctly?

### ISSUE THREAD

**Issue by dgwyer** [jeffreyvr/tailpress#15]
Just came across TailPress today. Nice work! I just had a couple of queries as I'm new to TailwindCSS JIT.

If you take a look at Adam's [YouTube video](https://www.youtube.com/watch?v=3O_3X7InOw8&t=336s) he's removed all the base styles to make the styles added by the JIT compiler clearer.

So, these were removed:

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

I did the same in TailPress so I could see the JIT compiler in action. However, when I removed the base styles and updated the styles in JS or PHP files, no classes from JS or PHP were added to the compiled CSS .

![TailPress](https://user-images.githubusercontent.com/1482075/113041991-8a829b00-9192-11eb-84dc-09ee5d6032e0.gif)

I can though, add custom styles directly to `resources/css/app.css` and these get compiled and added to `css/app.css`.

Am I missing something? If I understand it correctly, with the base styles removed, then we should still be able to see the TailwindCSS classes pulled from the JS and PHP and compiled into `css/app.css`?

Also, apart from the CSS reset, shouldn't we be removing the base styles by default anyway as this is JIT compilation so we should be adding _only_ the classes used in the content (JS and PHP) rather than all base styles as we did pre TailwindCSS JIT.

**Comment by jeffreyvr** [comment]
I think that Adam means he just removed `@import "tailwindcss/base";`, not all imports. If you leave the others in, you will get the effect as seen in the video.

Quick example: https://youtu.be/vBhyv-9va5s

Ps. If you wan't it to pick up on Tailwind classes inside JS-files to (in your gif you are changing `app.js`), you would have to add it to the purge list in `tailwind.config.js`. But you might have already known that :-)

**Comment by dgwyer** [comment]
Yes, that's true for the JS files but in the GIF above I'm editing a PHP file too and those classes aren't being compiled for some reason as in your video. Not sure why.

**Comment by jeffreyvr** [comment]
Just to be sure, do you have these two uncommented?:

```css
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

**Comment by dgwyer** [comment]
Got it. Thanks for clarifying.
