### ISSUE TITLE
Gutenberg Styles not applying on front end

### ISSUE THREAD

**Issue by joelgrodriguez** [jeffreyvr/tailpress#16]
WordPress 5.7
NGINX
PHP 7.4
tailpress 0.0.8

Installed a fresh copy and added some blocks and styles to a post. 
Did not edit any theme files at all. Ran dev build, then production.

Styles are applied when viewing in the Gutenberg editor but not on front end. 

<img width="1150" alt="Screen Shot 2021-04-05 at 8 25 33 AM" src="https://user-images.githubusercontent.com/28833044/113584853-a51ca000-95e8-11eb-8f74-9c81435ef9d8.png">
<img width="1574" alt="Screen Shot 2021-04-05 at 8 25 20 AM" src="https://user-images.githubusercontent.com/28833044/113584861-a8179080-95e8-11eb-83b2-be64911491a3.png">

What is the best way to achieve this? I would like for styles applied on the block editor to apply on the front end. 

Thanks

**Comment by jeffreyvr** [comment]
Hi @joelgrodriguez,

Thanks for reporting! I hadn't noticed it yet, but apparently, the [JIT (Just in time) engine](https://tailwindcss.com/docs/just-in-time-mode) that was recently introduced by Tailwind CSS does not yet support the [safe list option](https://tailwindcss.com/docs/just-in-time-mode#known-limitations) for PurgeCSS.

So these options in the `tailwind.config.js` are ignored. 

```js
purge: {
   options: {
      safelist: {
         standard: [/^has-/, /^align/, /^wp-/]
      }
},
```

This results in all the classes for the Block editor / Gutenberg missing.

There are two options basically:

1) Not use the JIT engine, which you can disable by settings mode to `aot` in `tailwind.config.js`. (Make sure you are using Tailwind CSS v2.1). However, disabling JIT will dramatically increase the compiling times.

2) Add a safelist file in which all the Gutenberg/Block editor classes are listed to prevent them from being purged. This is the approach I have taken. Check out this commit https://github.com/jeffreyvr/tailpress/commit/11be5a40476c44c562230f16345a635b13895191.
