### ISSUE TITLE
npm run watch-sync requires to force browser cache to see changes

### ISSUE THREAD

**Issue by pixeline** [jeffreyvr/tailpress#162]
Hi!

When developing the theme, I use `npm run watch-sync` . Browser reload when saving a watched file works fine but the changes are not visible until i force a hard browser cache refresh .
![image](https://user-images.githubusercontent.com/393415/206418341-77df060b-3721-4bca-b239-177b1bf36ec7.png)

I was wondering if there is a way to have it done automatically or to not have the browser cache interfere ?

**Comment by jeffreyvr** [comment]
Hi! This is not something I'm able to reproduce (tested Safari and Chrome). Should work like this:

https://user-images.githubusercontent.com/9550079/206429922-6eb0f7c7-8e23-49b0-bdcf-48e81c8d3238.mov

**Comment by charlie-george-1989** [comment]
![Screenshot 2022-12-08 at 23 29 14](https://user-images.githubusercontent.com/69805219/206588475-7ba1af4b-3460-4575-bc01-b1666ce67f01.png)

You could try disabling cache like this

**Comment by jeffreyvr** [comment]
Timestamp will be added if you set the environment type to 'development' (https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/).

**Comment by pixeline** [comment]
@jeffreyvr thank you very much, that did the trick!
