### ISSUE TITLE
Some Tailwind Classes Not Present?

### ISSUE THREAD

**Issue by pageworthy** [jeffreyvr/tailpress#18]
I'm new to tailwind but so far I'm loving it, so thank you for your work in bringing it to WP. After running "npm run watch" and the previous commands most things seem to work, and I was able to add custom fonts and other styles. 

However, in trying to add a grid layout with something like: <div class="grid grid-cols-4 gap-4"> the "grid" classes are not available and do nothing. Same with things like border-color that are built into tailwind from their docs.

Am I missing a step or is there an import I'm supposed to add to bring in all the available Tailwind classes?

**Comment by jeffreyvr** [comment]
In which files are you using those classes? Make sure that the files you edit are defined within the purge content option:

https://github.com/jeffreyvr/tailpress/blob/master/tailwind.config.js#L9

**Comment by pageworthy** [comment]
I was trying to add them directly in Gutenberg. It's okay, I was able to set up Codekit to compile tailwind and it works as expected with all of the classes available in development as expected.

**Comment by sameraw** [comment]
I am having the same issue... i cannot use grid. For example:
`wp_enqueue_script( 'tailpress', tailpress_asset( 'js/app.js' ), array(), $theme->get( 'Version' ) );` 
causes the grid element to look like this:
![Screenshot 2024-08-22 at 6 43 20 PM](https://github.com/user-attachments/assets/1cc7b579-3050-4ec9-93c4-28e74105b613)

When I remove it and add the regular tailwind library: 
`wp_enqueue_script( 'tailpress', tailpress_asset( 'js/tailwind.js' ), array(), $theme->get( 'Version' ) ); `
It looks fine:
![Screenshot 2024-08-22 at 6 43 29 PM](https://github.com/user-attachments/assets/92ab0303-2770-4a9c-b148-ba1971740745)
there seems to be missing CSS classes native to tailwind.
