### ISSUE TITLE
Avoiding using deprecated global Mix

### ISSUE THREAD

**Issue by KawanSoares** [jeffreyvr/tailpress#197]
I don't have permission to make the change so here is my suggestion:
At [webpack.mix.js](https://github.com/jeffreyvr/tailpress/blob/de76aba76b178773d6773a8941ae9537e00203b8/webpack.mix.js#L31C7-L31C7)

`
    Mix.manifest.refresh = _ => void 0
`
Change to:
`
    mix.options({ manifest: false })
`

**Comment by jeffreyvr** [comment]
Has been changed, thanks for the suggestion!
