### ISSUE TITLE
Custom JIT classes not working

### ISSUE THREAD

**Issue by Blusoup** [jeffreyvr/tailpress#20]
Hi Jeffrey,

Thank you so much for creathing this theme!

Just a couple of questions: 
Apologies if you've already covered them.
I can't seem to add custom classes with JIT. Do I need to activate it somewhere? I looked on the JIT github and it does not look the same as yours in the `tailwind.config.js` and I can't find the `postcss.config.js`. I'm sure I'm doing something wrong. 

Thaks very much for your help

**Comment by Blusoup** [comment]
I think I have figured out the problem... 
I commented out the `custom.css` in the `app.css` file and it all seem to work fine now. 

Is this correct?

**Comment by jeffreyvr** [comment]
Hi @Blusoup,

You should't have to remove `custom.css` for it to work. Just did a quick test adding a custom class, and that seems to work fine.

See: https://www.youtube.com/watch?v=1yL0mnmMhkE

If you mean something else, please let me know.

**Comment by Blusoup** [comment]
Weirdly it seems to be workifng fine now. Honestly it did not, but I am happy that it is now. 

What do you use to auto reload your browser on save? Or do you just refresh it manually?

Thank you.

**Comment by jeffreyvr** [comment]
I mostly refresh manually, but you can uncomment the browsersync bit in the `webpack.mix.js`:

https://github.com/jeffreyvr/tailpress/blob/master/webpack.mix.js#L22

**Comment by Blusoup** [comment]
Amazing, thank you very much
