### ISSUE TITLE
Bowser-sync missing or removed?

### ISSUE THREAD

**Issue by remondevries** [jeffreyvr/tailpress#209]
It looks like in the new version of the theme the "browser sync" feature is removed. When I check the package.json it looks like its not there anymore?

When I check the readme.md it still lists this npm script as a option. Maybe I am missing something but I think it be good to keep "browser-sync" in the package. But if for what ever reason it needs to be removed it would be good to also remove it fully from the docs.

**Comment by jeffreyvr** [comment]
Hi! It's a usable command when you use the non-default esbuild version of TailPress (https://github.com/jeffreyvr/tailpress-installer/blob/master/stubs/esbuild/package.json.stub#L27). However, it should be document better. Will change that soon.

**Comment by jeffreyvr** [comment]
I assumed it was still in the readme, but after checking it looks it was already removed. If I'm over looking something, please let me know.

In short, if you use TailPress with Laravel Mix (default), you can enable Browser sync through:
https://github.com/jeffreyvr/tailpress/blob/master/webpack.mix.js#L21

When using the esbuild version, you can use `npm run browser-sync`.
