### ISSUE TITLE
watch production

### ISSUE THREAD

**Issue by teamcrisis** [jeffreyvr/tailpress#21]
Is there a way to npm watch and output production files?

I'm seeing many issues with `postcss-nested` due to `PostCSS 8` that do not happen in development but do happen in production.

It's very annoying to code up an entire site and then switch to production run and find many issues with the css because of bugs in `postcss-nested`. 

There are several open issues on the `postcss-nested` repo about the problem.

**Comment by jeffreyvr** [comment]
I can imagine that's annoying. I don't know if that is possible to be honest. If you find out anything feel free to share here. Maybe others have run into issues with PostCSS-nested as wel. So far I haven't luckily.

As this is not a specific issue with TailPress, I will close this for now.
