### ISSUE TITLE
incompatible with php 8.3

### ISSUE THREAD

**Issue by pixeline** [jeffreyvr/tailpress#218]
composer complains and aborts when launching 

````
composer global require jeffreyvanrossum/tailpress-installer
````

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - friendsofphp/php-cs-fixer is locked to version v2.10.0 and an update of this package was not requested.
>     - friendsofphp/php-cs-fixer v2.10.0 requires php ^5.6 || >=7.0 <7.3 -> your php version (8.3.6) does not satisfy that requirement.
>   Problem 2
>     - phpspec/prophecy v1.6.2 requires php ^5.3|^7.0 -> your php version (8.3.6) does not satisfy that requirement.
>     - phpunit/phpunit 4.8.35 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[v1.6.2].
>     - phpunit/phpunit is locked to version 4.8.35 and an update of this package was not requested.
> 
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require jeffreyvanrossum/tailpress-installer:*" to figure out if any version is installable, or "composer require jeffreyvanrossum/tailpress-installer:^2.1" if you know which you need.
>

**Comment by JonasBrandit** [comment]
Hi @jeffreyvr 

Any news about this?

**Comment by joelgrodriguez** [comment]
composer global require jeffreyvanrossum/tailpress-installer --with-all-dependencies 

fixed it for me.

**Comment by jeffreyvr** [comment]
I can install tailpress-installer with php 8.3 without any issues.

Looks like some other packages you have installed globally are not compatible with PHP 8.3, such as phpunit v4 and php-cs-fixer v2. TailPress installer is not requiring those.

**Comment by jeffreyvr** [comment]
Closing this for now.
