### ISSUE TITLE
Loses styles every couple days

### ISSUE THREAD

**Issue by mstrong64** [jeffreyvr/tailpress#231]
Tailpress Version 0.0.4. WP 6.6.2

Every couple of days my website breaks because Tailpress loses its styles somehow. I have to go in and clear the cache and then refresh the site. If this keeps up I will have to remove Tailpress from the site! Not something I want to have to do. Is there a permanent fix for this?

**Comment by jeffreyvr** [comment]
Unfortunately there is an inrelated plugin with the same name as this theme (theme was around way before the plugin), I think the issue you are having is with that plugin.

**Comment by mstrong64** [comment]
Ah, sorry didn't realise. Thanks for your reply.
