### ISSUE TITLE
Wrong path on CSS background image

### ISSUE THREAD

**Issue by jomsky** [jeffreyvr/tailpress#29]
My path for images in the theme is on `mytheme/resources/images`. 
If I try to build `background-image: url('../images/shuttle.png');` the output becomes `background-image: url('/images/shuttle.png?d4a53ce1e7463f4937d167599ed4763f');` So because it's the wrong path the image does not display. 

Any idea why this happens and how to solve it?

**Comment by jeffreyvr** [comment]
If you add `mix.setResourceRoot('../');` to your `webpack.mix.js` file, it should then resolve to the correct location.

Will probably add that as a default soon.

**Comment by jomsky** [comment]
That worked. Thank you!
