### ISSUE TITLE
Error when trying to define new value for default color

### ISSUE THREAD

**Issue by danielbehrendt** [jeffreyvr/tailpress#30]
When I try to set a new value for i.e. "blue" in tailpress.json 

```
{
    "colors": {
        "blue": "#77a9c1"
    }
}
```

and then run

` npm run development` 

I'm getting an error:

```
The `text-blue-500` class does not exist, but `text-gray-500` does. If you're sure that `text-blue-500` 
exists,  make sure that any `@import` statements are being properly processed before Tailwind CSS 
sees your CSS,  as `@apply` can only be used for classes in the same CSS tree.
```

Any idea how to overwrite the value of an existing color?

**Comment by jeffreyvr** [comment]
It will conflict with the classname of the Tailwind colors itself as it turns out. Workaround would be to use a different name or to remove the blue colors from your tailwind.config.js.

**Comment by jeffreyvr** [comment]
As I'm not really sure what TailPress should do with this, I'm going to close this issue. If anyone has an idea, feel free to share it.
