### ISSUE TITLE
Browser-sync

### ISSUE THREAD

**Issue by dapunkt** [jeffreyvr/tailpress#36]
When running 'npm run watch',  with Browsersync enabled, I see the following message in terminal:
"[Browsersync] File event [change] : css/app.css" 

But I have to reload my browserwindow manually?? How come?

**Comment by jeffreyvr** [comment]
Try adding `injectChanges: false` to your browserSync config (in `webpack.mix.js`).

**Comment by dapunkt** [comment]
Doesn’t work, I am using localwp with vscode and safari!

**Comment by dapunkt** [comment]
Added:

files: ["*.php"],
injectChanges: false

And now it works!

Thx,


Steven

**Comment by MaxCSwann** [comment]
Adding on a comment here in case it helps anyone. 

I'm not exactly sure what my issue was but it seemed that nested files weren't being watched using just `[files](files: ["*.php"],)"` .

Instead, `files: ['**/*'],` seemed to do the trick. I'd imagine you may want to use this with some caution though as you might not need to watch every single file in the theme.
