### ISSUE TITLE
 static testing = false;

### ISSUE THREAD

**Issue by mangomkt** [jeffreyvr/tailpress#7]
When running development or watch I get this error

 static testing = false;

**Comment by jeffreyvr** [comment]
This probably due to using an old version of Node. See this issue on the Laravel Mix repo:

https://github.com/JeffreyWay/laravel-mix/issues/2570

**Comment by vlados** [comment]
I am using node v15.8.0 (npm v7.5.4) on CentOS and getting the same error. Tried and with v14
