### ISSUE TITLE
rm -rf .git not a command on windows

### ISSUE THREAD

**Issue by mangomkt** [jeffreyvr/tailpress#8]
I was wondering if you could help me with this issue

rm -rf .git not a command on windows

**Comment by jeffreyvr** [comment]
The idea behind that command is to delete `.git` folder once you have cloned the repository.

I'm not a Windows user so I can't test a Windows variant of this. Maybe just `rmdir .git`? (From the theme directory of course)

If you can verify this works I'll mention it in the readme, or feel free to do a pull request to add it.
