### ISSUE TITLE
Additional classes not working

### ISSUE THREAD

**Issue by IonutRealDevs** [jeffreyvr/tailpress#88]
Nothing happens when I add tailwind classes on paragraph/heading additional classes in admin...

**Comment by jeffreyvr** [comment]
Tailwind CSS won't pick up classes that are used within the admin, since they are not used within files of your theme. 

If you wan't to use classes in your admin, you'll need to whitelist those classes you are using. You can do so by adding them in your `safelist.txt` file.

**Comment by IonutRealDevs** [comment]
Oh, i see, thank you.
