### ISSUE TITLE
Tailwind partially built, missing css class

### ISSUE THREAD

**Issue by khelil** [jeffreyvr/tailpress#97]
After building assets with `npm run dev` can't have access to all tailwind default class (eg [tailwindcss padding](https://tailwindcss.com/docs/padding)). 

Example the `p{t|r|b|l}-{size}` class is not generated for all spacing, only having some in the final theme css.

<img width="181" alt="Capture d’écran 2022-03-17 à 10 59 31" src="https://user-images.githubusercontent.com/28292/158784861-6b0868db-f5a6-427a-a02e-5fdc981f3e3f.png">

Tried to specify spacing in theme.json with no results...any ideas ?

**Comment by julianlaibach** [comment]
Hey Khelil, please have a look into your tailwind.config.js. If you have jit enabled the npm run dev / prod / watch will only include the used css classes. If you want to have the complete tailwind.css framework (wich i wouldnt recommend) you need to turn off jit (just in time) mode

[](https://v2.tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode)

**Comment by jeffreyvr** [comment]
To add to @julianlaibach, JIT is enabled by default is you are using Tailwind CSS v3. The current version of TailPress is using Tailwind v3.

**Comment by khelil** [comment]
Thank you @julianlaibach @jeffreyvr got it now, and it works fine 🚀
